### ISSUE TITLE
SIM PIN dialog does not pop up automatically

### ISSUE THREAD

**Issue by erikinkinen** [droidian/oFono2MM#1]
When a locked SIM card is inserted into the phone, no unlocking dialog appears. This bug cannot be reproduced on a PinePhone running real ModemManager and it can only be reproduced some devices.

More specifically, I can reproduce this on google_sargo but not on volla_yggdrasil.

**Comment by erikinkinen** [comment]
Also, when unlocked through gnome-control-center, one has to restart gnome-control-center to open modem settings. (shows as SIM locked otherwise)

**Comment by JamiKettunen** [comment]
Can confirm this on my MSM8998 OnePlus 5T phone.

**Comment by erikinkinen** [comment]
> Can confirm this on my MSM8998 OnePlus 5T phone.

I've noticed that this is reproducible also on yggdrasil after updating phosh to 0.10.1.

**Comment by FakeShell** [comment]
fixed with latest gsettings tweaks. closing
