### ISSUE TITLE
High cpu usage upon startup

### ISSUE THREAD

**Issue by FakeShell** [droidian/oFono2MM#10]
ofono2mm seems to consume a lot of cpu during startup before ofono completely comes up. there are no errors or anything to post as information.
this behaviour isnt specific to Droidian as it also happens on manjaro libhybris and alphybris.

**Comment by erikinkinen** [comment]
@FakeShell , could you debug it further? I would like to know what it is doing to eat up so much CPU.

**Comment by FakeShell** [comment]
Issue happens when ofono crashes or the service for ofono has been stopped (or its on startup and ofono2mm is waiting for ofono to start)
When ofono comes up and can list contexts then everything goes back to normal

**Comment by FakeShell** [comment]
Issue happens when ofono crashes or the service for ofono has been stopped (or its on started and ofono2mm is waiting for ofono to start)
When ofono comes up and can list contexts then everything goes back to normal
