### ISSUE TITLE
Pip install?

### ISSUE THREAD

**Issue by ghost** [droidian/oFono2MM#12]
Might not be necessary, but it's easier in my mind to work with pip than debuild. Also likely allows for more portablility.

**Comment by ghost** [comment]
Nevermind. It would seem that debian does not allow for pip installations to the system.

**Comment by erikinkinen** [comment]
Using a pip package would be harder when generating rootfs images. Also, it is for a good reason newer pip versions do not allow modifying system package manager managed installation without explicitly forcing it.

Also, it is just a better practice to package it as a Debian package like all other Python packages the system depends on.
