### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by JamiKettunen** [droidian/oFono2MM#8]
As per https://github.com/droidian/oFono2MM/blob/feature/bookworm/initial-implementation/debian/copyright the source code is licensed under a [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html), yet the repository root is missing a `LICENSE` file, which is required to be distributed along with installed binaries.

**Comment by erikinkinen** [comment]
https://github.com/droidian/oFono2MM/commit/a244e47ed2acf259a84100c73bea2bded73d56d1 adds a LICENSE file to the root of repository.
